(ns citytrail.core
  (:require
   [ajax.core :as ajax]
   [reagent.core :as reagent :refer [atom]]
   [reagent.session :as session]
   [reitit.frontend :as reitit]
   [clerk.core :as clerk]
   [accountant.core :as accountant]))

;; -------------------------
;; Routes

(def router
  (reitit/router
   [["/" :index]
    ["/items"
     ["" :items]
     ["/:item-id" :item]]
    ["/about" :about]]))

(defn path-for [route & [params]]
  (if params
    (:path (reitit/match-by-name router route params))
    (:path (reitit/match-by-name router route))))

(path-for :about)
;; -------------------------
;; Page components

(defonce wow (reagent/atom {:cities 0 :trails 0}))

(defn handler [response]
  (js/alert (str response)))

(defn error-handler [{:keys [status status-text]}]
  (js/alert (str "Ouch: " status " - " status-text)))

(defn load-wow []
  (ajax/POST "https://my-project-1550937209990.appspot.com/location/search"
             {:params          {:query "CN Tower"}
              :handler         #(reset! wow %)
              :error-handler   error-handler
              :format          :json
              :response-format :json
              :keywords?       true
              }))

(defn button []
  [:button.btn
    {:on-click load-wow}
    "Guide Me"])

(defn yah []
  [:div
    [:h1 "Yah"]
    [:p (str @wow)]
    [button]])

(defn kelson [text]
  [:div
    [:h3 "TESTING " text]
    [:p "testing again"]])

(defn home-page []
  (fn []
    [:span.main
     [:h1 "Welcome to citytrail"]
     [:ul
      [:li [:a {:href (path-for :items)} "Items of citytrail"]]
      [:li [:a {:href "/borken/link"} "Borken link"]]]
     [yah]
     [kelson "A"]
     [kelson "B"]]))



(defn items-page []
  (fn []
    [:span.main
     [:h1 "The items of citytrail"]
     [:ul (map (fn [item-id]
                 [:li {:name (str "item-" item-id) :key (str "item-" item-id)}
                  [:a {:href (path-for :item {:item-id item-id})} "Item: " item-id]])
               (range 1 60))]]))


(defn item-page []
  (fn []
    (let [routing-data (session/get :route)
          item (get-in routing-data [:route-params :item-id])]
      [:span.main
       [:h1 (str "Item " item " of citytrail")]
       [:p [:a {:href (path-for :items)} "Back to the list of items"]]])))


(defn about-page []
  (fn [] [:span.main
          [:h1 "About citytrail"]]))


;; -------------------------
;; Translate routes -> page components

(defn page-for [route]
  (case route
    :index #'home-page
    :about #'about-page
    :items #'items-page
    :item #'item-page))


;; -------------------------
;; Page mounting component

(defn current-page []
  (fn []
    (let [page (:current-page (session/get :route))]
      [:div
       [:header
        [:p [:a {:href (path-for :index)} "Home"] " | "
         [:a {:href (path-for :about)} "About citytrail"]]]
       [page]
       [:footer
        [:p "citytrail was generated by the "
         [:a {:href "https://github.com/reagent-project/reagent-template"} "Reagent Template"] "."]]])))

;; -------------------------
;; Initialize app

(defn mount-root []
  (reagent/render [current-page] (.getElementById js/document "app")))

(defn init! []
  (clerk/initialize!)
  (accountant/configure-navigation!
   {:nav-handler
    (fn [path]
      (let [match (reitit/match-by-path router path)
            current-page (:name (:data  match))
            route-params (:path-params match)]
        (reagent/after-render clerk/after-render!)
        (session/put! :route {:current-page (page-for current-page)
                              :route-params route-params})
        (clerk/navigate-page! path)
        ))
    :path-exists?
    (fn [path]
      (boolean (reitit/match-by-path router path)))})
  (accountant/dispatch-current!)
  (mount-root))
